### ISSUE TITLE
Account activation fails, token expired

### ISSUE THREAD

**Issue by bwulff** [overleaf/overleaf#819]
## Steps to Reproduce

1. login as admin
2. create an account by entering an email address under `/admin/register`
3. open the mail send by sharelatex and click on the activation link
4. enter a password for the new account

## Expected Behaviour
Account is activated and user can use sharelatex.

## Observed Behaviour
A red error box appears indicating that "the token has already expired", even though the token was generated seconds before. 

## Context
Creating user accounts for my colleagues after setting up the deployment according to the Quick Start guide and with the `docker-compose.yml` from this repo. 

## Technical Info

* URL: company internal
* Browser Name and version: FireFox 81.0.1
* Operating System and version (desktop or mobile): macOS 10.14.16
* Docker Host OS: Ubuntu 18.04
* Docker: 19.03.04
* docker-compose: 1.27.4
* Image: sharelatex/sharelatex:6e6f3526af69

## Analysis

This sounds exactly like the issue: https://github.com/overleaf/docker-image/issues/63
However, the thread had no other information about the fix but that it was working in version 0.6.1 of the container and the ticket was closed subsequently. 

I know that time/date are sometimes an issue in Docker containers so I validated that time and date are correct inside the container (using `date`).

**Comment by bwulff** [comment]
Also found this issue: https://github.com/overleaf/web/issues/392

In that and the other issue some say that the accounts are in fact activated despite the error message. This is not true in my case. I tried to login with the password I tried to set and it does not work.

**Comment by bwulff** [comment]
Fixed: Using not the image from Docker Hub but building `sharelatex-base` and `sharelatex` locally from source (284a6e9@master) solved the problem. 

..maybe the image on Docker Hub is outdated.

**Comment by bwulff** [comment]
Issue is not seen in the current Docker image (see last comment). Thus closing this.

**Comment by bwulff** [comment]
Reopening because now it doesn't work any more. Token is expired even seconds after the generation.

Workaround: After the activation has failed, users can actually navigate to the "password forgotten" link, acquire a password reset link and set their password this way.

**Comment by mserranom** [comment]
Thanks for the report @bwulff, there's some extra information that could be useful:
- The version of mongo you're running
- web service logs (`/var/log/sharelatex/web.log`). It should cover both attempts,  registration and activation.
- The output of `db.tokens.find({'data.email': 'example@example.com'}).sort({createdAt: 1}).pretty()`  after registration (for an email that fails to activate afterwards)

**Comment by jdleesmiller** [comment]
(Note: if you'd like to provide that info privately, you can send an email to support@overleaf.com mentioning this ticket.)

**Comment by sjewo** [comment]
I had the same problem. 
It worked for me after using all lowercase emails (the problem is mentioned in this issue: https://github.com/overleaf/web/issues/741)

**Comment by mserranom** [comment]
This should be fixed in the latest 2.5.2 release

https://github.com/overleaf/overleaf/tree/master/hotfix/2.5.2

**Comment by HanwGeek** [comment]
> This should be fixed in the latest 2.5.2 release
> 
> https://github.com/overleaf/overleaf/tree/master/hotfix/2.5.2

Hi, I still have this problem with sharelatex2.7.0. What can I do to fix this problem? Thanks!
